#!/usr/bin/env bash
# Shebang for better file detection

# Just guessing, there's zero information on the architecture of this image.
BASE_ARCH="arm64"

# Third party OrangePi 4 Raspberry Pi OS image.
DOWNLOAD_URL_CHECKSUM="https://gist.githubusercontent.com/miklschmidt/eb0dee54e204a8e5c030f5f4b2976588/raw/6cfe7cde0896fdd25b2b3f9a81ecf3d33cd5ddcb/Orangepicm4_1.0.0_raspios_bullseye_server_linux5.10.160.7z.sha256"
DOWNLOAD_URL_IMAGE="https://github.com/leeboby/raspberry-pi-os-images/releases/download/opicm4/Orangepicm4_1.0.0_raspios_bullseye_server_linux5.10.160.7z"

# export variables
export BASE_ARCH
export DOWNLOAD_URL_CHECKSUM
export DOWNLOAD_URL_IMAGE
