#!/usr/bin/env bash
# Installs Klipper_linear_movement_analysis
########

set -xe

# shellcheck source=/dev/null
source /common.sh
# shellcheck source=/dev/null
source "${RATOS_EXTERNAL_HELPER}"
install_cleanup_trap

echo_green "Installing Klipper Linear Movement Analysis by MarschallMarc#6420"

pushd "/home/${BASE_USER}"

gitclone LINEAR_MOVEMENT_ANALYSIS klipper_linear_movement_analysis

EXTENSION_PATH="/home/${BASE_USER}/klipper_linear_movement_analysis"
SCRIPT_NAME="linear_movement_vibrations.py"

register_klippy_extension "linear_movement_analysis" "${EXTENSION_PATH}" "${SCRIPT_NAME}"

echo_green "Installing matplotlib for python 2"

/home/"${BASE_USER}"/klippy-env/bin/pip install -v matplotlib
