#!/usr/bin/env bash
#### CB1SPI - SB1 Configuration Module
#from https://www.reddit.com/r/BIGTREETECH/comments/xfom6n/comment/it32e6v/

# shellcheck enable=require-variable-braces

## Source error handling, leave this in place
set -Ee

# Set DEBIAN_FRONTEND to noninteractive
if [[ "${DEBIAN_FRONTEND}" != "noninteractive" ]]; then
    export DEBIAN_FRONTEND=noninteractive
fi

## Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

echo_green "Enable SPI interface on CB1 SBC's ..."

# Step 1: Copy default config to backup file
cp "${CB1SPI_CONFIG_TXT_FILE}" "${CB1SPI_CONFIG_BAK_FILE}"

# Step 2: Enable SPI
sed -i 's/^#overlays=spidev1_2.*/overlays=spidev1_2/' "${CB1SPI_CONFIG_TXT_FILE}"

echo_green "Enable SPI interface on CB1 SBC ... DONE!"